### ISSUE TITLE
Package into cocoapod or carthage package

### ISSUE THREAD

**Issue by electic** [funky-monkey/IsoCountryCodes#7]

**Comment by funky-monkey** [comment]
Fork it and make pull request 😉

**Comment by RobSwish** [comment]
This is a fantastic little thing. Really really useful! Obviously it is so light weight a cocoapod seems overkill but it would be cool! 

If you could integrate Stripe that would be awesome. What I mean by this is that you could pass in that you only want to search for Stripe countries etc because Stripe only supports X amount of countries. 

If I ever get time I may look at raising a pull request! Never made a cocoapod before but I'll give it a shot.

**Comment by funky-monkey** [comment]
@RobSwish can you explain a little more about 'integrating Stripe'? Or you just need a list/property that returns `true` when Stripe is available?

**Comment by funky-monkey** [comment]
I'll close this because @dmazzoni created #12
